name: Deploy Nuget Registry

  - name: Pack
    run: dotnet pack Authentication/Nexttag.Utils.Authentication/Nexttag.Utils.Authentication.csproj -c Release

  - name: Prep packages
    run: dotnet nuget add source --username jordaobass --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nexttag/index.json"
    
  - name: Publish to GitHub packages
    run: dotnet nuget push Authentication/Nexttag.Utils.Authentication/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"