name: .NET 5 + Pack + Push no NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./Nexttag.Utils.Database/Nexttag.Utils.Database.csproj
      URL_NUGET: https://nuget.pkg.github.com/nexttag/index.json

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget add source ${{ env.URL_NUGET }}  -n github -u JORDAOBASS -p PAT 
#        dotnet nuget push *.nupkg --api-key ${{ secrets.WORKFLOW_NUGET_AUTH }} --source ${{ env.URL_NUGET }} --skip-duplicate
        
        
