name: Build and deploy MeuPacote Package

on:
  push:
    branches:
      - main

jobs:
    build-and-deploy-database:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/nexttag/index.json
          filters: |
            workflows:
              - './Nexttag.Utils.Database/**'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH_DATABASE_POSTGRES: ./Nexttag.Utils.Database/Nexttag.Utils.Database.csproj

      - name: workflow tests
        if: steps.filter.outputs.workflows == 'true'
        run: echo "Change file"

    # run only if not 'workflows' files were changed
      - name: not workflow tests
        if: steps.filter.outputs.workflows != 'true'
        run: echo "NOT change file"
      
      - name: Build with dotnet
        run: dotnet build ./Nexttag.Utils.Database/Nexttag.Utils.Database.csproj --configuration Release

      - name: Create the Package
        run: dotnet pack ./Nexttag.Utils.Database/Nexttag.Utils.Database.csproj --configuration Release

      - name: Publish
        run: dotnet nuget push "Nexttag.Utils.Database/bin/Release/*.nupkg" -k ${{secrets.WORKFLOW_NUGET_AUTH}} -s https://nuget.pkg.github.com/nexttag/index.json --skip-duplicate

    build-and-deploy-database-postgres:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/nexttag/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH_DATABASE_POSTGRES: ./Nexttag.Utils.Database/Nexttag.Utils.Database.Postgres.csproj

      - name: Build with dotnet
        run: dotnet build ${{env.PATH_DATABASE_POSTGRES}} --configuration Release

      - name: Create the Package
        run: dotnet pack ${{env.PATH_DATABASE_POSTGRES}} --configuration Release

      - name: Publish
        run: dotnet nuget push "Nexttag.Utils.Database/bin/Release/*.nupkg" -k ${{secrets.WORKFLOW_NUGET_AUTH}} -s https://nuget.pkg.github.com/nexttag/index.json --skip-duplicate
